# Uncomment the next line to define a global platform for your project
platform :ios, '16.0'

target 'MyWidgetExtension' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  # Pods for MyWidgetExtension

end

target 'UIKitTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  # Pods for UIKitTest

end
